openapi: 3.0.3
info:
  title: Portfolio API
  version: 1.0.0
  description: A CRUD API for managing portfolio data
paths:
  /portfolio:
    get:
      summary: Get all portfolio items
      responses:
        '200':
          description: OK
    post:
      summary: Create a new portfolio item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PortfolioItem'
      responses:
        '201':
          description: Created
    put:
      summary: Update an existing portfolio item
      parameters:
        - in: query
          name: id
          schema:
            type: string
          required: true
          description: The ID of the portfolio item to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PortfolioItem'
      responses:
        '200':
          description: OK
    delete:
      summary: Delete an existing portfolio item
      parameters:
        - in: query
          name: id
          schema:
            type: string
          required: true
          description: The ID of the portfolio item to delete
      responses:
        '204':
          description: No Content
  /portfolio/{id}:
    get:
      summary: Get a specific portfolio item
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The ID of the portfolio item to retrieve
      responses:
        '200':
          description: OK
    put:
      summary: Update an existing portfolio item
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The ID of the portfolio item to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PortfolioItem'
      responses:
        '200':
          description: OK
    delete:
      summary: Delete an existing portfolio item
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The ID of the portfolio item to delete
      responses:
        '204':
          description: No Content
components:
  schemas:
    PortfolioItem:
      type: object
      properties:
        websiteTitle:
          type: string
        title:
          type: string
        description:
          type: string
        callToAction:
          type: string
        projects:
          type: array
          items:
            $ref: '#/components/schemas/Project'
        technologySummary:
          type: string
        technologies:
          type: array
          items:
            $ref: '#/components/schemas/Technology'
        aboutMe:
          type: string
        workExperiences:
          type: array
          items:
            $ref: '#/components/schemas/WorkExperience'
        email:
          type: string
    Project:
      type: object
      properties:
        projectTitle:
          type: string
        projectImage:
          type: string
        projectDescription:
          type: string
        visitLink:
          type: string
        sourceLink:
          type: string
        stacks:
          type: array
          items:
            type: string
    Technology:
      type: object
      properties:
        technologyTitle:
          type: string
        technologyDescription:
          type: string
    WorkExperience:
      type: object
      properties:
        timelineYear:
          type: string
        timelineDescription:
          type: string

